# Generated by Django 4.2.7 on 2023-11-10 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('eye_color', models.CharField(max_length=20)),
                ('hair_color', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('eye_colors', models.CharField(max_length=255)),
                ('hair_colors', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('original_title_romanised', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=4)),
                ('running_time', models.PositiveIntegerField()),
                ('rt_score', models.PositiveIntegerField()),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.species'),
        ),
    ]
